run:
  timeout: 5m
  modules-download-mode: vendor
  skip-files:
    - '.*_test.go'

linters:
  enable:
    - prealloc
    - dogsled
    - exportloopref
    - unconvert
    - unparam
    - whitespace
    - bodyclose
    - gosec
    - forcetypeassert
    - goconst
    - makezero
    - sqlclosecheck
linters-settings:
  gosec:
    excludes:
      - G307
      - G304